# Generated by Django 5.2.8 on 2025-12-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do campeão')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função do campeão')),
                ('descricao', models.TextField(verbose_name='Descrição do campeão')),
            ],
        ),
    ]
